// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using masterdata.Models;

namespace masterdata.Migrations
{
    [DbContext(typeof(MasterDataContext))]
    partial class MasterDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("masterdata.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("client_id");

                    b.Property<string>("Application")
                        .HasColumnName("application");

                    b.Property<int>("Enabled")
                        .HasColumnName("enabled");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasColumnName("username");

                    b.HasKey("ClientId");

                    b.ToTable("client");
                });

            modelBuilder.Entity("masterdata.Models.SnowCostCenterResults.Result", b =>
                {
                    b.Property<int>("result_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("result_id");

                    b.Property<string>("AssociationTime")
                        .HasColumnName("association_time");

                    b.Property<string>("CostCenterDescription")
                        .HasColumnName("cost_center_description");

                    b.Property<string>("LegalEntity")
                        .HasColumnName("legal_entity");

                    b.Property<string>("LegalEntityDescription")
                        .HasColumnName("legal_entity_description");

                    b.Property<string>("OrganizationalUnitCode")
                        .HasColumnName("organizational_unit_code");

                    b.Property<string>("OrganizationalUnitDescription")
                        .HasColumnName("organizational_unit_description");

                    b.Property<string>("OrganizationalUnitType")
                        .HasColumnName("organizational_unit_type");

                    b.Property<string>("Typology")
                        .HasColumnName("typology");

                    b.HasKey("result_id");

                    b.ToTable("result");
                });
#pragma warning restore 612, 618
        }
    }
}
